# This section replaces lines 317-336 in your playbook.yml
      register: scaphandre_task

# End of "Setup Node 1" play

# If you want to fetch from node1 to controller then to node3, create separate plays:
- name: Fetch results from Node 1
  hosts: node1
  remote_user: root
  tasks:
    - name: Fetch results to controller
      fetch:
        src: /root/experiments_summary_dbserver.json
        dest: /tmp/experiments_summary_dbserver.json
        flat: yes

- name: Copy results to Node 3
  hosts: node3
  remote_user: root
  tasks:
    - name: Create directory for fixed JSON files
      file:
        path: /root/fixed_json_files
        state: directory
        mode: '0755'
        
    - name: Copy results from controller to Node 3
      copy:
        src: /tmp/experiments_summary_dbserver.json
        dest: /root/fixed_json_files/experiments_summary_dbserver.json

# Continue with Setup Node 2 play
- name: Setup Node 2
  hosts: node2
  remote_user: root
  tasks: 